### ISSUE TITLE
Create default of producing 'CITATION.cff' in root, and work on root POM

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#1]
Per default, the dependencies meta info (i.e., the THIRD PARTY folder) should be created in root, and the citation info be written into a file called `CITATION.cff` (the only valid file name for a CFF file), which should also be placed in the root dir of the project.

**Comment by thomaskrause** [comment]
This is already solved by using the `${basedir}/CITATION.cff` and `${basedir}/THIRD-PARTY` defaults in the Maven parameters. These are also now documented in the README.
