### ISSUE TITLE
Don't overwrite primary authors' info

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#11]
ATM, the author info of the project that the plugin is run on overwrites any author info (and other metadata) for the project.

Once this info is curated, existing info shouldn't be touched, only new info added.
This is also related to #4.

**Comment by thomaskrause** [comment]
This can be solved by specifying a template CITATION.cff input file with the `input` parameter (https://github.com/hexatomic/cff-maven-plugin#cffcreate). The fields existing in the extended input file will not be overridden.
