### ISSUE TITLE
mvn cff:create doesn't update information

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#29]
See https://github.com/hexatomic/hexatomic/issues/392: running `mvn cff:create` doesn't yield the expected results. Instead, the contents of a template overwrite any existing information.

Expected behaviour:
- `cff:create` should update information:
    - Dependencies
    - `date-released` (build-related)
    - `version` (build-related)

**Comment by thomaskrause** [comment]
I think the underlying issue in hexatomic/hexatomic#392 was an update in Tycho. This plugin does support some Tycho idiosyncrasies, but if the dependency information is not provided at all as Maven dependency by Tycho, there is nothing this plugin can do.

When fixing hexatomic/hexatomic#392 I noticed another P2-related bug in this plugin, which got a separate issue: #30 

Please re-open if I misunderstood the scope of this issue.
