### ISSUE TITLE
Implement automatic CFF updates which don't break the manual curation state

### ISSUE THREAD

**Issue by sdruskat** [hexatomic/cff-maven-plugin#4]
There should be an automated way to update existing information in the CFF file.

This mostly concerns version numbers, but may concern the author list as well (authors between versions may change).

**Comment by thomaskrause** [comment]
We now have reference templates (https://github.com/hexatomic/cff-maven-plugin#curated-reference-templates) which can be used for this purpose. These templates mean you can re-create the CITATION.cff files completely, without loosing the manually curated information in the template.
